"""Add cascade delete to shipment status history

Revision ID: 205dedf96534
Revises: 69889a00d896
Create Date: 2025-04-15 14:48:39.459171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205dedf96534'
down_revision = '69889a00d896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_status_history', schema=None) as batch_op:
        batch_op.drop_constraint('shipment_status_history_shipment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'export_request', ['shipment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_status_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shipment_status_history_shipment_id_fkey', 'export_request', ['shipment_id'], ['id'])

    # ### end Alembic commands ###
