"""add shipment status history table

Revision ID: 69889a00d896
Revises: 
Create Date: 2025-02-12 18:57:52.064598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69889a00d896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_status_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shipment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['export_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('export_request_backup')
    op.drop_table('item_detail_backup')
    op.drop_table('shipments_backup')
    op.drop_table('users_backup')
    op.drop_table('export_request_temp')
    with op.batch_alter_table('export_request', schema=None) as batch_op:
        batch_op.alter_column('status_changed_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='References the user who last changed the shipment status',
               existing_nullable=True)
        batch_op.alter_column('status_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the shipment status was last changed',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_shipment_status_tracking')
        batch_op.create_index(batch_op.f('ix_export_request_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_request_status_changed_by'), ['status_changed_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_request_status_changed_by'))
        batch_op.drop_index(batch_op.f('ix_export_request_created_by'))
        batch_op.create_index('idx_shipment_status_tracking', ['status_changed_by', 'status_changed_at'], unique=False)
        batch_op.alter_column('status_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the shipment status was last changed',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status_changed_by',
               existing_type=sa.UUID(),
               comment='References the user who last changed the shipment status',
               existing_nullable=True)

    op.create_table('export_request_temp',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('waybill_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('sender_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sender_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receiver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('receiver_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('receiver_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('receiver_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('receiver_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('destination_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_postcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('freight_pricing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('additional_charges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pickup_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('handling_fees', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insurance_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_collection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_group', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_booked_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('users_backup',
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('shipments_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('waybill_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('sender_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sender_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receiver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('receiver_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('receiver_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('receiver_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('receiver_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('destination_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_postcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('freight_pricing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('additional_charges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pickup_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('handling_fees', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insurance_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_collection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_group', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_booked_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('item_detail_backup',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('export_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('export_request_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('waybill_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('sender_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sender_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receiver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('receiver_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('receiver_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('receiver_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('receiver_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('destination_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_postcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('freight_pricing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('additional_charges', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pickup_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('handling_fees', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insurance_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_collection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_group', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_booked_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('shipment_status_history')
    # ### end Alembic commands ###
